force-app/main/default/objects/Project__c/fields/Bill_by__c.field-meta.xml
<CustomField>
    <fullName>Bill_by__c</fullName>
    <label>Bill by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Bill_By_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Budget_By__c.field-meta.xml
<CustomField>
    <fullName>Budget_By__c</fullName>
    <description>The method by which the project is budgeted.</description>
    <label>Budget By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Budget_By_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client for project</description>
    <inlineHelpText>Client for project</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the project is billable or not.</description>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Project_Bill_By_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Project</fullName>
        <default>true</default>
        <label>Project</label>
    </customValue>
    <customValue>
        <fullName>Tasks</fullName>
    </customValue>
    <customValue>
        <fullName>People</fullName>
    </customValue>
    <customValue>
        <fullName>none</fullName>
    </customValue>
    <masterLabel>Project Bill By Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Project_Budget_By_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>project</fullName>
        <default>true</default>
        <label>Project</label>
    </customValue>
    <customValue>
        <fullName>project_cost</fullName>
        <label>Project cost</label>
    </customValue>
    <customValue>
        <fullName>task</fullName>
        <label>Task</label>
    </customValue>
    <customValue>
        <fullName>task_fees</fullName>
        <label>Task fees</label>
    </customValue>
    <customValue>
        <fullName>person</fullName>
        <label>Person</label>
    </customValue>
    <customValue>
        <fullName>none</fullName>
        <label>None</label>
    </customValue>
    <masterLabel>Project Budget By Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TimeEntriesTestDataFactory.cls
/**
 * Supplies and populates the database with entities
 * needed for testing
 *
 * What do we need for testing TimeEntries?
 *
 * A test user who is a normal user of the application (not a PM)
 * A test user who is a system administrator
 * A test use who is a project manager on a project
 * Clients, Projects, and Tasks.
 *
 */
@isTest
public class TimeEntriesTestDataFactory {

  // TODO: Should this be moved to UserTestDataFactory?
  /**
   */

  // TODO: Should this be moved to ProjectsTestDataFactory?

  /**
   * Creates projects and dependent client Accounts for testing
   * <p>
   * If numberOfProjects is less than or equal to zero, nothing is done
   * and an empty list of projects is returned.
   *
   * @author Raphael Krausz
   * @param  numberOfProjects the number of projects to create
   * @param  isBillable true means the project should be billed
   * @param  billBy must be one of: 'Project', 'Tasks', 'People', 'none'
   * @param  budgetBy must be one of: 'project', 'project_cost', 'task', 'task_fees', 'person', 'none'
   * @return A List of Project__c
   */
  public static List<Project__c>
  createProjectsAndClients(Integer numberOfProjects,
                           Boolean isBillable,
                           String  billBy,
                           String  budgetBy) {

    if (numberOfProjects <= 0) return new List<Project__c>();

    // We need to know where to start our index at
    Integer numberOfExistingTestClients =
    Database.countQuery('SELECT Count()'
                        + ' FROM Account'
                        + ' WHERE Name LIKE \'TestClient\\%\'');


    // Setup client Accounts
    List<Account> clients  = new List<Account>();

    for (Integer i = 1 + numberOfExistingTestClients;
         i <= numberOfProjects + numberOfExistingTestClients;
         i++)
    {
      Account client  = new Account(Name='TestClient' + i);
      clients.add(client);
    }

    insert clients;


    // Create the projects
    List<Project__c> projects = new List<Project__c>();
    for (Account client : clients) {
      Project__c project = new Project__c(Name = 'TestProject'
                                          + 'For' + client.Name,
                                          Client__c = client.Id,
                                          Is_Billable__c = isBillable,
                                          Bill_by__c = billBy,
                                          Budget_By__c = budgetBy);
      projects.add(project);
    }

    insert projects;

    return projects;
  }


  /**
   * Creates projects and dependent client Accounts for testing
   * where each project is billable by Project and budgeted by Project
   * <p>
   * If numberOfProjects is less than or equal to zero, nothing is done
   * and an empty list of projects is returned.
   *
   * @author Raphael Krausz
   * @param  numberOfProjects the number of projects to create
   * @return A List of Project__c
   */
  public static List<Project__c>
  createProjectsAndClients(Integer numberOfProjects) {
    return createProjectsAndClients(numberOfProjects, true, 'Project', 'project');
  }


}