force-app/main/default/objects/Project__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>The budget in hours for the project when budgeting by time.</description>
    <label>Budget</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description>Rate for projects billed by Project Hourly Rate.</description>
    <label>Hourly Rate</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the project is active or archived.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/Project_User_Assignment__c.object-meta.xml
<CustomObject>
    <description>Assigns user to a Project.</description>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>PUA-{0000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_User_Assignment__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>Budget used when the project’s budget_by is person</description>
    <inlineHelpText>Budget used when the project’s budget_by is person</inlineHelpText>
    <label>Budget</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description>Rate used when the project’s bill_by is People.</description>
    <inlineHelpText>Rate used when the project’s bill_by is People.</inlineHelpText>
    <label>Hourly Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the user assignment is active or archived.</description>
    <inlineHelpText>Whether the user assignment is active or archived.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Is_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Is_Project_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the user has project manager permissions for the project.</description>
    <inlineHelpText>Determines if the user has project manager permissions for the project.</inlineHelpText>
    <label>Project Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The Project associated with the User</description>
    <inlineHelpText>The Project associated with the User</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project User Assignments</relationshipLabel>
    <relationshipName>Project_User_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user associated with the project</description>
    <inlineHelpText>The user associated with the project</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_User_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectUserAssignmentsTest.cls
/**
 * Tests ProjectUserAssignments domain layer
 * <p>
 * Required fields:
 * Project__c
 * User__c
 * <p>
 * Optional fields and defaults:
 * Is_Active__c          - true
 * Is_Project_Manager__c - false for regular users
 * Is_Project_Manager__c - true  for system administrators
 * Is_Project_Manager__c - true  for project managers
 * Hourly_Rate__c        - defaults to 0
 * Budget__c             - no default
 * <p>
 * Note: We are not testing defaults for project managers
 * or system administrators at the moment as it is outside
 * of scope for our current work. (?)
 *
 * @author Raphael Krausz
 * @date   2018-05-20
 */
@isTest
private class ProjectUserAssignmentsTest {

  /**
   * Test an assignment can be made with just a project and a user
   * <p>
   * "Happy path" - tests success when project and user are supplied
   */
  @isTest static void testMinimumAssignmentCreation() {

    // Grab a test user and a test project
    Test.startTest();
    User testUser = TimeEntriesTestDataFactory.createTestUsers(1)[0];
    Project__c testProject = TimeEntriesTestDataFactory.createProjectsAndClients(1)[0];
    Test.stopTest();

    System.assertNotEquals(null, testUser.Id);
    System.assertNotEquals(null, testProject.Id);

    // Assign the user to the project, expect success
    Project_User_Assignment__c testAssignment =
    new Project_User_Assignment__c(Project__c = testProject.Id,
                                   User__c    = testUser.Id);

    Test.startTest();
    try {
      insert testAssignment;
    } catch (Exception e) {
      System.assert(false,
                    'We tried to create a project user assignment, '
                    + 'with just a user and project, '
                    + ' but an exception was thrown');
      System.debug('Exception caught: ' + e);
      return;
    }
    Test.stopTest();

    // Expect the defaults are correctly set
    System.assert(testAssignment.Is_Active__c, 'Assignment not active');
    System.assertEquals(false, testAssignment.Is_Project_Manager__c, 'regular Assignment set to PM');
    System.assertEquals(0, testAssignment.Hourly_Rate__c, 'Hourly rate not 0');
    System.assertEquals(null, testAssignment.Budget__c, 'Budget filled in');
  }
}