force-app/main/default/objects/Project__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>The budget in hours for the project when budgeting by time.</description>
    <label>Budget</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description>Rate for projects billed by Project Hourly Rate.</description>
    <label>Hourly Rate</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the project is active or archived.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/Project_User_Assignment__c.object-meta.xml
<CustomObject>
    <description>Assigns user to a Project.</description>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>PUA-{0000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_User_Assignment__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>Budget used when the project’s budget_by is person</description>
    <inlineHelpText>Budget used when the project’s budget_by is person</inlineHelpText>
    <label>Budget</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description>Rate used when the project’s bill_by is People.</description>
    <inlineHelpText>Rate used when the project’s bill_by is People.</inlineHelpText>
    <label>Hourly Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the user assignment is active or archived.</description>
    <inlineHelpText>Whether the user assignment is active or archived.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Is_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Is_Project_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the user has project manager permissions for the project.</description>
    <inlineHelpText>Determines if the user has project manager permissions for the project.</inlineHelpText>
    <label>Project Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The Project associated with the User</description>
    <inlineHelpText>The Project associated with the User</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project User Assignments</relationshipLabel>
    <relationshipName>Project_User_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user associated with the project</description>
    <inlineHelpText>The user associated with the project</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_User_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectUserAssignments.cls
/**
 * Domain layer for assigning users to a project
 * <p>
 * Directly correlates to Harvest's "Project User Assignments"
 * and the "User Project Assignments" models
 *
 * @author Raphael Krausz
 * @date   2018-05-20
 */
public class ProjectUserAssignments extends fflib_SObjectDomain {

  // public ProjectUserAssignments(List<Project_User_Assignment__c> sObjectList) {
  //   super(sObjectList);
  // }

  // public class Constructor implements fflib_SObjectDomain.IConstructable {
  //   public fflib_SObjectDomain construct(List<SObject> sObjectList) {
  //     return new ProjectUserAssignments(sObjectList);
  //   }
  // }

  // /**
  //  * Apply Defaults to Project User Assignments
  //  * <p>
  //  * Auto-populated data on create and update
  //  * <p>
  //  * Optional fields defaults:
  //  * Is_Active__c          - true
  //  * Is_Project_Manager__c - false for regular users
  //  * Is_Project_Manager__c - true  for system administrators*
  //  * Is_Project_Manager__c - true  for project managers*
  //  * Hourly_Rate__c        - defaults to 0
  //  * <p>
  //  * * PM and sys admin defaults not implemented yet for
  //  * the Is_Project_Manager__c field (out of current scope)
  //  * <p>
  //  * At the moment, Is_Active__c and Is_Project_Manager__c are handled
  //  * by the SF object defaults.
  //  *
  //  */
  // public override void onApplyDefaults() {

  //   for(Project_User_Assignment__c puc : (List<Project_User_Assignment__c>) Records) {
  //     if (puc.Hourly_Rate__c == null)
  //       puc.Hourly_Rate__c = 0;

  //   }
  // }


  // public override void onValidate() {

  //   List<Id> projectIdList = new List<Id>();
  //   List<Id> userIdList    = new List<Id>();

  //   for(Project_User_Assignment__c puc : (List<Project_User_Assignment__c>) Records) {
  //     projectIdList.add(puc.Project__c);
  //     userIdList.add(puc.User__c);
  //   }



  // }



}

/*
 * Required fields:
 *
 * Project__c
 * User__c
 *
 *
 * Defaults - default values for optional fields:
 *
 * Is_Active__c - true
 * Is_Project_Manager__c - false for regular users
 * Is_Project_Manager__c - true  for system administrators
 * Is_Project_Manager__c - true  for project managers
 * Hourly_Rate__c        - defaults to 0
 *
 * No default on: Budget__c
 *
 */