force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client for project</description>
    <inlineHelpText>Client for project</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the project is active or archived.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProjectsSelector.cls
/**
* Selector for Projects
* @author Raphael Krausz
* @date 2018-05-17
*/

public class ProjectsSelector extends fflib_SObjectSelector {

  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      Project__c.Id,
      Project__c.Client__c,
      Project__c.Is_Active__c
    };
  }


  public Schema.SObjectType getSObjectType() {
    return Project__c.sObjectType;
  }

  public List<Project__c> selectById(Set<ID> idSet) {
    return (List<Project__c>) selectSObjectsById(idSet);
  }

}