force-app/main/default/objects/Project__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the project is active or archived.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/Project_User_Assignment__c.object-meta.xml
<CustomObject>
    <description>Assigns user to a Project.</description>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>PUA-{0000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_User_Assignment__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the user assignment is active or archived.</description>
    <inlineHelpText>Whether the user assignment is active or archived.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The Project associated with the User</description>
    <inlineHelpText>The Project associated with the User</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project User Assignments</relationshipLabel>
    <relationshipName>Project_User_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_User_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user associated with the project</description>
    <inlineHelpText>The user associated with the project</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_User_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectUserAssignmentsSelector.cls
/**
* Selector for Project User Assignments
* @author Raphael Krausz
* @date 2018-05-17
*/

public class ProjectUserAssignmentsSelector extends fflib_SObjectSelector {
  public ProjectUserAssignmentsSelector() {
    super(false);
  }



  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      Project_User_Assignment__c.Id,
      Project_User_Assignment__c.Name,
      Project_User_Assignment__c.Is_Active__c,
      Project_User_Assignment__c.Project__c,
      Project_User_Assignment__c.User__c
    };
  }

  public Schema.SObjectType getSObjectType() {
    return Project_User_Assignment__c.sObjectType;
  }


  /**
   * Given a user Id, return the active assignments for that user
   */
  public List<Project_User_Assignment__c>
  selectByUserId(Set<Id> userIdSet) {
    if (userIdSet == null || userIdSet.isEmpty()) {
      // We should either return an empty list,
      // null or raise an error (exception)
      return new List<Project_User_Assignment__c>();
    }

    return (List<Project_User_Assignment__c>)
    Database.query(newQueryFactory().
                   setCondition('User__c IN :userIdSet').
                   setCondition('Is_Active__c = true').
                   toSOQL());
  }


  // /**
  //  * Given a list of project Ids and a list of corresponding user Ids
  //  * return a list of Project User Assignments containing the
  //  * given inputs.
  //  * <p>
  //  * The lists must be of equal length and are paired with the
  //  * corresponding position in the list.
  //  * <p>
  //  * So, a project ID in position 0 of the product ID list corresponds
  //  * to the User ID in position 0 of the user ID
  //  */
  // public List<Project_User_Assignment__c>
  // selectByProjectAndUser(List<Id> projectIds, List<Id> userIds) {

  //   // if projectIds.size() != userIds.size - return error

  //   List<Project_User_Assignment__c> unfilteredResults =
  //   (List<Project_User_Assignment__c>)
  //   Database.query(
  //                  newQueryFactory().
  //                  selectField(Project_User_Assignment__c.Id).
  //                  selectField(Project_User_Assignment__c.Name).
  //                  selectField(Project_User_Assignment__c.Is_Active__c).
  //                  selectField(Project_User_Assignment__c.Project__c).
  //                  selectField(Project_User_Assignment__c.User__c).
  //                  // selectField('Project__r.Is_Active__c').
  //                  setCondition('Project__c in :projectIds').
  //                  setCondition('User__c in :userIds').
  //                  // setCondition('Is_Active__c = true').
  //                  // setCondition('Project__r.Is_Active__c = true').
  //                  toSOQL());

  //   Map<Id, Map<Id, Project_User_Assignment__c>> projectAndUserIdMap
  //   = new Map<Id, Map<Id, Project_User_Assignment__c>>();

  //   for (Project_User_Assignment__c assignment : unfilteredResults) {

  //     Id projectId = assignment.Project__c;
  //     Id userId = assignment.User__c;

  //     Map<Id, Project_User_Assignment__c> userIdToAssignmentMap;

  //     if (projectAndUserIdMap.containsKey(projectId)) {
  //       userIdToAssignmentMap = projectAndUserIdMap.get(projectId);
  //     } else {
  //       userIdToAssignmentMap = new Map<Id, Project_User_Assignment__c>();
  //     }

  //     userIdToAssignmentMap.put(userId, assignment);
  //     projectAndUserIdMap.put(projectId, userIdToAssignmentMap);
  //   }

  //   List<Project_User_Assignment__c> filteredResults = new List<Project_User_Assignment__c>();

  //   for (Integer i = 0; i < projectIds.size(); i++) {
  //     Id projectId = projectIds.get(i);
  //     Id userId    = userIds.get(i);

  //     if (! projectAndUserIdMap.containsKey(projectId) ) continue;
  //     Map<Id, Project_User_Assignment__c> userIdToProjectMap
  //     = projectAndUserIdMap.get(projectId);

  //     if (! userIdToProjectMap.containsKey(userId) ) continue;

  //     filteredResults.add(userIdToProjectMap.get(userId));

  //   }

  // }

}